[tool.poetry]
name = "agregator"
version = "0.1.0"
description = ""
authors = ["Shitikov Kirill"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
